---
run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    # - bodyclose
    # - deadcode
    # - depguard
    # - dogsled
    # - dupl
    - errcheck
    # - exhaustive
    # - funlen
    # - gas
    - gosec
    # - gochecknoinits
    - goconst
    # - gocritic
    # - gocyclo
    # - gofmt
    - goimports
    - revive
    # - gomnd
    # - goprintffuncname
    # - gosec
    - gosimple
    - govet
    - ineffassign
    # - lll
    # - megacheck --> gosimple, staticcheck, unused.
    - misspell
    # - nakedret
    # - noctx
    # - nolintlint
    # - rowserrcheck
    # - scopelint
    # - staticcheck --> TODO fix findings
    # - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    # - varcheck
    # - whitespace
  fast: false
