# https://goreleaser.com
project_name: tf-module-versions

before:
  hooks:
    - go mod tidy
    -

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X main.BuildVersion={{.Version}}
      - -s
      - -w
    dir: .
    binary: tf-module-versions

brews:
- name: tf-module-versions
  tap:
    owner: rollwagen
    name: tf-module-versions
  folder: Formula
  license: Apache-2.0

universal_binaries:
  - replace: true

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
