project_name: tf-module-versions

before:
  hooks:
    - ./scripts/completions.sh

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: tfm
    ldflags:
      - -s -w -X main.build={{.Version}}

brews:
  - tap:
      owner: rollwagen
      name: homebrew-tap
    license: Apache-2.0
    install: |-
      bin.install "tfm"
      bash_completion.install "completions/tfm.bash" => "tfm"
      zsh_completion.install "completions/tfm.zsh" => "_tfm"
      fish_completion.install "completions/tfm.fish"

checksum:
  name_template: 'checksums.txt'


archives:
  - files:
      - README.md
      - LICENSE
      - completions/*

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
