project_name: tf-module-versions

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: tfm
    ldflags:
      - -s -w -X main.build={{.Version}}

brews:
  - name: tf-module-versions
    tap:
      owner: rollwagen
      name: homebrew-tap
    license: Apache-2.0

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
