repos:

- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.0
  hooks:
  - id: go-imports
  # - id: go-fmt
  # - id: go-vet
  - id: go-mod-tidy
  - id: golangci-lint
  # - id: go-unit-tests

- repo: https://github.com/Bahjat/pre-commit-golang
  rev: v1.0.1
  hooks:
  - id: gofumpt # requires github.com/mvdan/gofumpt

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
