# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TfModuleVersions < Formula
  desc ""
  homepage ""
  version "0.0.3"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/rollwagen/tf-module-versions/releases/download/v0.0.3/tf-module-versions_0.0.3_darwin_all.tar.gz"
    sha256 "9a78ca91a014185658a138785c778633b2bd162a7b5fdb15f792455515be700f"

    def install
      bin.install "tf-module-versions"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rollwagen/tf-module-versions/releases/download/v0.0.3/tf-module-versions_0.0.3_linux_arm64.tar.gz"
      sha256 "db6227372f07dfface28ac61337aa37333833db3372130990ed77d8e006f8c3a"

      def install
        bin.install "tf-module-versions"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rollwagen/tf-module-versions/releases/download/v0.0.3/tf-module-versions_0.0.3_linux_amd64.tar.gz"
      sha256 "8de5a280c8dced428f53ee2e8aa9581e3c2347f15e633d1a4684ea9584b2e792"

      def install
        bin.install "tf-module-versions"
      end
    end
  end
end
