# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TfModuleVersions < Formula
  desc ""
  homepage ""
  version "0.0.5"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/rollwagen/tf-module-versions/releases/download/v0.0.5/tf-module-versions_0.0.5_darwin_all.tar.gz"
    sha256 "a3a63db60abd3342c639bd91836b26df12473e84ca0fa70ccd420d4fa8897e4e"

    def install
      bin.install "tf-module-versions"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rollwagen/tf-module-versions/releases/download/v0.0.5/tf-module-versions_0.0.5_linux_arm64.tar.gz"
      sha256 "bbc73692adff1b5a8568fa360d1715517820ffe80eb75705f70856e252cedf0e"

      def install
        bin.install "tf-module-versions"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rollwagen/tf-module-versions/releases/download/v0.0.5/tf-module-versions_0.0.5_linux_amd64.tar.gz"
      sha256 "e2705cabfacade98ead1763099f58f4c9537c19bf6040b471bdf09db932c0a33"

      def install
        bin.install "tf-module-versions"
      end
    end
  end
end
