# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfmodver < Formula
  desc ""
  homepage ""
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/rollwagen/tf-module-versions/releases/download/v0.0.1/tf-module-versions_0.0.1_darwin_all.tar.gz"
    sha256 "012a89c69f2b653d86318c8f1d46d0c6ce5fe626ef0688c2ace63e9d826bb1f5"

    def install
      bin.install "tf-module-versions"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rollwagen/tf-module-versions/releases/download/v0.0.1/tf-module-versions_0.0.1_linux_amd64.tar.gz"
      sha256 "1eebaea1dcfbba03ede9ef4d79ec2471a49f42b34787517ebdf133b74b35e60f"

      def install
        bin.install "tfmodver"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rollwagen/tf-module-versions/releases/download/v0.0.1/tf-module-versions_0.0.1_linux_arm64.tar.gz"
      sha256 "9949e99c456065105666805625cada2d3250c9196577093a2c09ff7fb7203e5c"

      def install
        bin.install "tfmodver"
      end
    end
  end
end
